AWSTemplateFormatVersion: "2010-09-09"
Resources:
  GithubInfo:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS ElasticBeanstalk application for GithubInfo
  GithubInfoConfiguration:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref GithubInfo
      Description: AWS ElasticBeanstalk configuration template for GithubInfo
      SolutionStackName: 64bit Amazon Linux 2 v3.4.15 running Docker
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref GithubInfoInstanceProfile
  GithubInfoEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref GithubInfo
      Description: AWS ElasticBeanstalk Environment for GithubInfo
      TemplateName: !Ref GithubInfoConfiguration
  GithubInfoInstanceRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service:
                - ec2.amazonaws.com
            Action:
              - sts:AssumeRole
      Description: Beanstalk EC2 role
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWebTier
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkMulticontainerDocker
        - arn:aws:iam::aws:policy/AWSElasticBeanstalkWorkerTier
  GithubInfoInstanceProfile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Roles:
        - !Ref GithubInfoInstanceRole
  GithubInfoAssetsBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: githubinfoassets
