AWSTemplateFormatVersion: "2010-09-09"
Parameters:
  InstanceProfileName:
    Type: String
Resources:
  GithubInfo:
    Type: AWS::ElasticBeanstalk::Application
    Properties:
      Description: AWS ElasticBeanstalk application for GithubInfo
  GithubInfoConfiguration:
    Type: AWS::ElasticBeanstalk::ConfigurationTemplate
    Properties:
      ApplicationName: !Ref GithubInfo
      Description: AWS ElasticBeanstalk configuration template for GithubInfo
      OptionSettings:
        - Namespace: aws:autoscaling:launchconfiguration
          OptionName: IamInstanceProfile
          Value: !Ref InstanceProfileName
      SolutionStackName: 64bit Amazon Linux 2 v3.4.15 running Docker
  GithubInfoEnvironment:
    Type: AWS::ElasticBeanstalk::Environment
    Properties:
      ApplicationName: !Ref GithubInfo
      Description: AWS ElasticBeanstalk Environment for GithubInfo
      TemplateName: !Ref GithubInfoConfiguration
