name: Publish API docker image to github container registry

env:
  USER_NAME: hassanzhd
  PIPELINE_ID: ${GITHUB_RUN_ID}-${GITHUB_RUN_NUMBER}
  APP_NAME: GithubInfoStack-GithubInfo-1RC2J2SU6EGBP
  S3_BUCKET: githubinfoassets
  AWS_REGION: us-east-1
  AWS_PLATFORM: Docker

on:
  push:
    branches: [main]

jobs:
  publish-api-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login docker into the github container registry
        run: |
          echo ${{secrets.PERSONAL_ACCESS_TOKEN}} | docker login ghcr.io -u ${{env.USER_NAME}} --password-stdin
      - name: Build the api docker image
        run: |
          docker build ./api --tag ghcr.io/hassanzhd/githubinfo_api:${{env.PIPELINE_ID}}
      - name: Push the api docker image
        run: |
          docker push ghcr.io/hassanzhd/githubinfo_api:${{env.PIPELINE_ID}}

  create-eb-version:
    needs: [publish-api-image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-id: ${{ secrets.AWS_ID }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: |
          AWS_VERSION_LABEL=${{env.APP_NAME}}-${{env.PIPELINE_ID}}
          S3_KEY="$AWS_VERSION_LABEL.yaml"

          echo "Uploading Source Bundle to S3"
          aws s3 cp docker-compose.yaml s3://${{env.S3_BUCKET}}/${S3_KEY} --region ${{env.AWS_REGION}}

          echo "Creating Elastic Beanstalk version"
          aws elasticbeanstalk create-application-version --application-name ${{env.APP_NAME}} --version-label $AWS_VERSION_LABEL --region ${{env.AWS_REGION}} --source-bundle S3Bucket=${{env.S3_BUCKET}},S3Key=${S3_KEY} --auto-create-application

  deploy-aws:
    needs: [create-eb-version]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.6 (needed for eb cli)
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-id: ${{ secrets.AWS_ID }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - run: |
          AWS_VERSION_LABEL=${{env.APP_NAME}}-${{env.PIPELINE_ID}}

          echo "Installing Elastic Beanstalk Cli"
          python -m pip install --upgrade pip
          pip install awsebcli --upgrade
          eb --version

          mkdir -p ~/.ssh/
          echo "${{ secrets.EC2_KEY }}" >> ~/.ssh/GithubInfoKey.pem
          ls -a ~/.ssh/

          echo "Deploy init"
          eb init -i ${{env.APP_NAME}} -p ${{env.AWS_PLATFORM}} -k ${{secrets.AWS_ID}} --region ${{env.AWS_REGION}}
          eb deploy ${{env.APP_NAME}} --version ${AWS_VERSION_LABEL}
          echo "Deploy finished"
